name: Security Audit

on:
  schedule:
    # Run weekly on Mondays at 3 AM UTC
    - cron: '0 3 * * 1'
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  security-audit:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level=moderate

    - name: Check for outdated packages
      run: npm outdated || true

    - name: Run dependency check
      run: |
        echo "## 🔒 Security Audit Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Dependency Status" >> $GITHUB_STEP_SUMMARY
        npm audit --audit-level=moderate --json > audit-results.json || true
        if [ -f audit-results.json ]; then
          vulnerabilities=$(jq '.metadata.vulnerabilities.total' audit-results.json)
          echo "- **Total vulnerabilities:** $vulnerabilities" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Outdated Packages" >> $GITHUB_STEP_SUMMARY
        npm outdated --json > outdated.json || true
        if [ -f outdated.json ]; then
          outdated_count=$(jq 'length' outdated.json)
          echo "- **Outdated packages:** $outdated_count" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-audit-${{ github.run_number }}
        path: |
          audit-results.json
          outdated.json
        retention-days: 30
